name: 'JIRA Release Notes'
description: 'Preparing release notes for JIRA'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
outputs:
  notes: # output will be available to future steps
    description: 'Release Notes String'
runs:
  using: 'node16'
  main: 'dist/index.js'
