name: "Test GA"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:
env:
  JIRA_PROJECT_KEY: 'WP'
  JIRA_URL: 'https://koia.atlassian.net'
  JIRA_PASS_PWA: ${{ secrets.JIRA_PAT }}
  JIRA_USER: 'filip.jakubowski@gmail.com'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    # Higher versions of checkout action are not working
    - uses: actions/checkout@v1
    - run: npm install
    - name: Get Release Notes
      uses: ./
      id: notes
    - name: Comment PR
      if: steps.notes.outputs.notes != ''
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          Notes: ${{ steps.notes.outputs.notes }}
